import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import hexplayer from '../public/hexplayer.svg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hexify</title>
        <meta name="Hexify" content="Generated by create next app" />
      </Head>
      <div className={styles.hexplayer}>
        <Image src={hexplayer} alt='hex' />
      </div>
      
    </div>
  )
}
